module.exports = {
    CONNECT: '@@ws/CONNECT',    
    NEW_EVENT_REQUEST: '@@ws/NEW_EVENT',
    NEW_SUBSCRIBER_REQUEST: '@@ws/NEW_SUBSCRIBER',
    UNSUBSCRIBED_REQUEST: '@@ws/UNSUBSCRIBED',
    NEW_EVENT_SUCCESS: '@@server-ws/NEW_EVENT',
    NEW_SUBSCRIBER_SUCCESS: '@@server-ws/NEW_SUBSCRIBER',
    UNSUBSCRIBED_SUCCESS: '@@server-ws/UNSUBSCRIBED'
};
